### PR TITLE
Pages: Added EZoApp to Resources

### PR DESCRIPTION
**Pull request by joshoolin**
EZoApp is a mobile App building tool using jQuery Mobile including drag and drop design tool and code editor. Formerly we developed on http://jqmdesigner.appspot.com/ and now prepare to migrate to the new official site.

### CODE REVIEW

**Comment by arthurvr** [comment]
@agcolom @arschmitz This has been open for way too long. What do we think? Are we okay with this app joining that page?

**Comment by agcolom** [comment]
:+1:

**Comment by agcolom** [comment]
@arthurvr are you happy to land? (If not I can do this tomorrow)

**Comment by arthurvr** [comment]
Yup, there we go! Thanks @joshoolin (and @agcolom of course ;)

**Comment by joshoolin** [comment]
Thank you all :)

**Pull request closed without merging**
