### PR TITLE
Pages: add wq framework

### PR DESCRIPTION
**Pull request by sheppard**
Follow up to #31.  The documentation is finally ready!

### CODE REVIEW

**Comment by jaspermdegroot** [comment]
@sheppard Congrats :)

Do you mind making the description a little bit shorter (so it fits on one line) and start with a capital? Currently it looks like this:

image

Thanks!

**Comment by sheppard** [comment]
How's this?

**Comment by jaspermdegroot** [comment]
@sheppard 

Still too long:
image

I am going to change it to "Progressively-enhanced offline-first web apps for citizen science and crowdsourcing", OK?

**Comment by sheppard** [comment]
Oops, sorry - it worked on my screen, but then again I don't have a typical setup.  Anyway, I'm <strike>probably</strike> trying to fit too many concepts/keywords into one sentence.  Your suggestion is fine for now, thanks.

**Comment by jaspermdegroot** [comment]
No problem :)

:+1:

**Comment by jaspermdegroot** [comment]
Landed in https://github.com/jquery/jquerymobile.com/commit/35061901b5516322b82df5f4751b574b6da462d4

**Comment by sheppard** [comment]
Thanks!

**Pull request closed without merging**
