### PR TITLE
Pages: add `jqm4gwt` to `Apps & frameworks`

### PR DESCRIPTION
**Pull request by arthurvr**
Fixes https://github.com/jquery/jquerymobile.com/issues/98. cc @slavap

### CODE REVIEW

**Comment by arthurvr** [comment]
@slavap Is this a reasonable description of your project?

**Comment by slavap** [comment]
@arthurvr Sounds good. You can add one more sentence: Pure Java can be used for Web UI development.

**Comment by arthurvr** [comment]
> You can add one more sentence: Pure Java can be used for Web UI development.

Happy to add something like that, though Isn't that kinda baked into the idea of GWT?

**Comment by slavap** [comment]
Sure, but when Java developers see jQuery word, they are terrified by necessity to use JavaScript :-)

**Comment by arthurvr** [comment]
What do you think about this version, @slavap? @agcolom @arschmitz looking good?

**Comment by slavap** [comment]
@arthurvr Thank you! Looks good to me.

**Comment by agcolom** [comment]
:+1:

**Comment by arthurvr** [comment]
Merged and deployed. Thanks @slavap and @agcolom :)

**Pull request closed without merging**
